### PR TITLE
Build

### PR DESCRIPTION
**Pull request by willrogers**
Hi,

I work at Diamond Light Source and I'm looking at a few codes for machine models.

These commits tidy up the build a bit - they remove files generated during the build from Git and add them to the `.gitignore` file.

I think this is correct but you might know more than me.

Cheers,
Will Rogers

### CODE REVIEW

**Comment by jbengtsson** [comment]
Hi Will,

Do you plan to use the model/code?

Cheers,

Johan

**Comment by willrogers** [comment]
Hi Johan,

We have a 'virtual accelerator' here at Diamond written by James Rowland (I believe you knew him).  It uses an older version of tracy.  I'm now looking at updating it to use the latest version.  I also looked at SCSI, which seems to be a very similar thing (right now I just made our virtac work with SCSI).

I'm looking at other codes too - I'd like to have an accelerator model for use in Python.

Cheers,
Will

**Comment by jbengtsson** [comment]
Yes I did (know James).

At NSLS-II we named the local version of his Virtual Accelerator
J.M.S. (ICALEPS
2013
http://accelconf.web.cern.ch/AccelConf/ICALEPCS2013/papers/moppc156.pdf
and IPAC 2015
http://accelconf.web.cern.ch/AccelConf/IPAC2015/papers/tupma054.pdf).

It (NSLS-II) went into operation, so I am no longer working for them.

Yes SCSI was a prototype Python interface for Tracy-2,3 (James made a
prototype/demo of this as well). Based on work I recently did for FRIB,
State Univ. of Michigan though, I would do the Python interface differently
-> start over (including setting up automated unit testing in Python).

Depending on your goals, I might be interested in collaborating.

To update your Virtual Accelerator to the latest version should be
"straightforward", I think.

Cheers,

Johan

**Comment by jbengtsson** [comment]
I just noticed that you made your VA work with SCSI.

Note, I "broke" SCSI (numerically) in one of the last code changes (1+ year
back). Hence, the importance to have automated unit testing (for "rapid
prototyping", etc.). It was a prototype, so I would not use it.

The Tracy-3.5 on github is the latest version; something I will maintain,
based on needs.

One thing to consider, would be to replace "Numerical Recipes" with "GNU
Scientific Library"; already prototyped in SCSI.

Cheers,

Johan

**Comment by willrogers** [comment]
OK, I'll shift my virtac over to Tracy-3.5.

Are you interested in such pull requests as this one, or are they merely an annoyance?

**Comment by jbengtsson** [comment]
Sounds good.

But of course (I am interested).

Johan

**Comment by jbengtsson** [comment]
BTW, in case you run into any problem (with your VA upgrade), feel free to
contact me.

Regards,

Johan

**Pull request merged**
